### ISSUE TITLE
Cancel button isn't working

### ISSUE THREAD

**Issue by rubenferreira97** [djibe/clockpicker#6]
Cancel button isn't working at all. Same behavior in demo.

Steps to reproduce:
Initialize a clockpicker with autoclose = false;
Choose an hour.
Choose a minute.
Cancel.

Expected result:
Blank or previous value.

Actual results:
Cancelled value inserted.

**Comment by djibe** [comment]
Hey,
I know ;-) I'm not very good but I'll try again.
If you can post a Pull Request ;-)

**Comment by rubenferreira97** [comment]
@djibe For some reason this only happens when you minify the file. With the normal javascript file it's all alright.

Any thoughts?

**Comment by djibe** [comment]
Hi, in dist folder I updated bootstrap4-clockpicker.min.js.
Now Cancel button is working.
Thx for reporting bug due to minification.
